version: "3.3"
services:
  db:
    container_name: 0x0-db
    restart: always
    image: 0x0-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: 0x0-graphql
    restart: always
    image: 0x0-graphql
    build:
        context: ./graphql
    env_file:
        - ./.env
    depends_on:
        - db
    networks:
        - network
    ports:
        - 5433:5433
    command: [
      "--connection", "${DATABASE_URL}", 
      "--port", "5433", 
      "--schema", "_0x0",
      "--default-role", "_0x0_anonymous",
      "--jwt-secret", "${JWT_SECRET}",
      "--jwt-token-identifier", "_0x0.jwt_token",
      "--append-plugins", "postgraphile-plugin-connection-filter",
      "--enhance-graphiql",
    ]

  pgadmin:
    container_name: pgadmin_container
    restart: unless-stopped
    image: dpage/pgadmin4
    env_file:
        - ./.env
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - network

networks:
  network:

volumes:
  db:
  pgadmin: